#!/usr/bin/env bash
# A Bash script to transfer file from a client to a server
# Using the scp linux command, taking  the following arguments
# PATH_TO_FILE to be copied to server, USER on server IP of server
# LOCATION to copy to on server and PATH_TO_IDENTITY_FILE for user auth

if [ $# -lt 4 ]
	then
		echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
		exit 1
fi

# assigning paramentals to variables
path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# Disabling StrictHostKeyChecking

scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
