#!/usr/bin/env bash
# Bash script that installs nginx on an ubuntu machine.
# The scripts also configures the default webpage served to be "Hello World!"
# When request url matches /redirect_me, it redirects to my github channel.

sudo apt-get update -y

sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html

#Using sed command to make a redirections

string_for_replacement="server_name -;\n\trewrite ^\/redir
ect_me https:\/\/github.com\/donbless27 permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /e
tc/nginx/site-enabled/default

sudo service nginx restart
