#!/usr/bin/env bash
# Returns a custom header on request

sudo apt-get -y update
sudo apt-get -y install nginx

# Custom Response header
sudo sed -i "52i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
# Hello world
echo "Hello World!" | sudo tee /var/www/html/index.html
# Error Page
echo "Ceci n'est pas une page" > sudo /var/www/html/404.html
# Redirection
string_for_replacement="server_name -;\n\trewrite ^\/redirect_me https:\/\/github.com\/donbless27 permanent;"
sudo service nginx start 
